### ISSUE TITLE
Backtest for binance produces garbage

### ISSUE THREAD

**Issue by trisbele** [Ekliptor/WolfBot#32] opened 2019-11-14 20:00 UTC
I am still trying to get the open source version working - no success til yet.
On a semi working instance I have made a new backtests with binance data.

The backtest of pairs on binance don't work either for USDT_BTC nor for BTC_ATOM for example:

Configuration: MACD-Binance ("pair": "USDT_BTC", "marginTrading": false, "tradeTotalBtc": 1000)
Exchange: Binance
From: 07/01/2019 2:00 AM
To: 08/01/2019 1:00 AM
Start Balance: 2000
Slippage: 0.05

Start balance (BTC equivalent): 	0.18177125
Current balance (BTC): 	-101.40490396
Start balance (USDT): 	2000.00000000
Current balance (USDT): 	-1012782.49233102
Buy trades: 	0
Winning buy trades: 	0
Losing buy trades: 	0
Sell trades: 	431
Winning sell trades: 	0
Losing sell trades: 	0
Market exposure time (days): 	0
Market exposure time (hours): 	0
Market exposure time (percent): 	0
Coin holdings efficiency (in %): 	-55887.100
Market efficiency (in %): 	-9.200
Bot efficiency (in %): 	-50739.100
Bot vs Market efficiency (in %): 	-50729.900

Configuration: MACD-Binance ("pair": "BTC_ATOM", "marginTrading": false, "tradeTotalBtc": 0.15)
Exchange: Binance
From: 07/01/2019 2:00 AM
To: 08/01/2019 1:00 AM
Start Balance: 1
Slippage: 0.05

Start balance (ATOM equivalent): 	1977.84810127
Current balance (ATOM): 	-314.38701222
Start balance (BTC): 	1.00000000
Current balance (BTC): 	-0.11412249
Buy trades: 	8
Winning buy trades: 	0
Losing buy trades: 	0
Sell trades: 	16
Winning sell trades: 	0
Losing sell trades: 	0
Market exposure time (days): 	26.67
Market exposure time (hours): 	1.11
Market exposure time (percent): 	3.59
Coin holdings efficiency (in %): 	-115.900
Market efficiency (in %): 	-28.200
Bot efficiency (in %): 	-111.400
Bot vs Market efficiency (in %): 	-83.200

Backtests with Margin Trading on Bitfinex works.

**Comment by Ekliptor** [comment] 2019-11-15 01:57
Margin trading for Binance is currently not supported, as mentioned here https://wolfbot.org/features/exchanges/

I am waiting for this pull request to be merged so that they have a consistent API https://github.com/ccxt/ccxt/pull/5907

However, CCXT library allows you to override (almost) everything and such API params wheter to use margin/spot/futures can easily be overwritten  when calling `new ccxt.binance({...})`. So if this is urgent you can look into it yourself and submit a pull request to WolfBot. Also you need to increase `this.maxLeverage` in `Binance.ts` for WolfBot to make margin trading work (even during backtesting).

**Comment by trisbele** [comment] 2019-11-15 09:07
I know that on "normal" binance there is no margin trading. That's why there is the "marginTrading" setting to false.

I thought that when marginTrading is false the bot will do only "long" and "stop long" and no short/sell. Is this not the meaning of marginTrading": false?

**Comment by Ekliptor** [comment] 2019-11-15 09:26
Ah sorry, because of your last mention of Bitfinex margin trading I got confused. Yes `marginTrading": false?` will disable it. So this is a bug, that the balance goes below 0. Although it most certainly crosses that value "correctly", meaning your balance decreases properly and the strategy settings are not profitable.

But to be sure and to fix this issue later can you please paste your full config of this backtest? Is is the default `MACD-Binance.json` without modifications?

**Comment by trisbele** [comment] 2019-11-15 10:50
Yes I have used the default MACD-Binance.json and adjusted for the both test to:

For the USDT_BTC test
"tradeTotalBtc": 1000,
"pair": "USDT_BTC",

For the BTC_ATOM test
"tradeTotalBtc": 0.15,
"pair": "BTC_ATOM",

**Comment by trisbele** [comment] 2019-11-15 16:04
I got errors in log output 
 2019-11-15 16:55:04 - error: Error checking margin {"txt":"Margin trading is not supported.","exchange":"Binance"}

 I have set "marginTrading": false in config

**Comment by Ekliptor** [comment] 2019-11-16 23:32
fixed. Please update `Binance.ts`

**Comment by trisbele** [comment] 2019-11-18 10:27
I have updated bot to current version.

Still this error:
2019-11-18 11:19:04 - error: Error updating margin positions for realtime exchange Binance {"txt":"Margin trading is not supported.","exchange":"Binance"}

The change you have made is:
this.maxLeverage = 1.0;
instead of 
this.maxLeverage = 3.0;

Is binance only usable with a margin account?
Margin is new to binance! Why there is the setting "marginTrading": false,?

I just want to buy BTC with USDT - go long!
And sell the BTC back to USDT - close long, no short!

**Comment by Ekliptor** [comment] 2019-11-19 04:09
fixed in `AbsractExchange.ts`

However, even though this is shown as an error you should be able to ignore this

**Comment by Ekliptor** [comment] 2019-12-01 17:29
I also just released another fix for crediting money after orders got cancelled during backtest.
Does this problem still exist with latest version? Can't reproduce it anymore and will close it if no more issues occur.

**Closed** 2019-12-09 20:56 UTC
